name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # 🔐 Debe existir este secret en GitHub > Settings > Secrets > Actions
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_DUNE_0A951CB0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # PR comments/annotations
          action: "upload"

          ###### Rutas del proyecto (ajustadas a tu estructura) ######
          app_location: "frontend"   # carpeta del sitio estático
          api_location: "api"        # carpeta de Azure Functions (Python)
          output_location: "/"       # sin build (HTML/CSS/JS puros)
          ###### Fin de configuración ######
  
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_DUNE_0A951CB0F }}
          action: "close"